Implemented simple LLM chat service
DV1512/llm_backend pull request #2
Opened 2024-11-16 15:26 UTC by writemorecode

I have implemented a small service for LLM inference. The API is inspired by OpenAI's APIs, described here: https://platform.openai.com/docs/api-reference/chat. Currently, the API has a single endpoint which takes a prompt via JSON and returns a streamed response. The response is streamed via Server-Sent Events, and each chunk is wrapped in JSON containing the timestamp and unique ID of the response. LLM inference is done using the Kalosm library. Currently, we are using Meta's Llama 3.1 8B Instruct model.

Todo:

- Implement authentication
- Implement rate limiting
- Implement storing past conversations in database

I have also implemented a small file upload service. I will merge that code into this repo after this PR is merged.

2024-11-18 13:48 UTC, kebabohvo reviewed
Looks good to me.

2024-11-18 14:31 UTC, kebabohvo approved these changes
ok

2024-11-18 14:31 UTC, merged

2024-11-18 14:47 UTC, retrokiller543 requested changes

2024-11-18 14:47 UTC, retrokiller543 commented on Cargo.toml
> +env_logger = "0.11.5"
please use tracing to keep to the same structure as our other repositories, if there is a specific reason for not following the same conventions and using the same crates to solve the problem at hand please state why in a comment so we know why this decision was made

2024-11-18 14:47 UTC, retrokiller543 commented on src/main.rs
> +            .wrap(Logger::default())
See how we have done logging in the backend repo, for `tracing` there is a different middleware for logging

2024-11-18 14:47 UTC, retrokiller543 commented on src/main.rs
> +    .bind("[::1]:8000")?
why are we only binding on ipv6? could this not cause issues where it wont get requests when using ipv4?

2024-11-18 14:47 UTC, retrokiller543 commented on src/state.rs
> +        let model = Llama::builder()
is this an expensive operation, or memory hungry to have an instance of the chat open? if not we should try and use `thread_local`, having to lock the state for each request will make every other request hang until its done, this might still happen since we are not load balancing the llm on different machines but artificially introducing this bottleneck seems bad.

I think that if we cant fix this at least document that this is a bottleneck and that the api will only handle 1 request at a time due to this

2024-11-18 14:47 UTC, retrokiller543 commented on src/chat.rs
> +) -> impl Responder {
An idea might be to make this return an Result, to do it you need to make a new Error type that implements `ResponseError`

2024-11-19 13:59 UTC, writemorecode commented on src/state.rs
> +        let model = Llama::builder()
Yes, this needs to be fixed. Otherwise we will not be able to send multiple simultaneous requests.