Made some changes to allow usage of files when using /templated instead of /completions
DV1512/llm_backend pull request #4
Opened 2024-11-20 09:49 UTC by kebabohvo

Added multiple services and functionality, so that we can use /templated for templated requests to the LLM.

Added some comments into README.
Added a ThreatActor struct into State, added a Vector containing these actors. Made so that the state is loaded with the data from data.json. Added 2 files, data.json and prompt.json , rudemantry test usage and will be expanded upon.

2024-11-20 10:23 UTC, retrokiller543 requested changes

2024-11-20 10:23 UTC, retrokiller543 commented on src/chat.rs
> +        .expect("Prompt not found for the given name");
Return an error if this happens, throwing the error will only result in the user seeing that there was an internal error when in actually they probably sent incorrect data

2024-11-20 10:23 UTC, retrokiller543 commented on src/chat.rs
> +        .expect("Group not found in the state");
same here with handling the error and returning it

2024-11-20 10:23 UTC, retrokiller543 commented on src/chat.rs
> +    prompt: String, // The custom prompt the user provides
remove GPT comment 😉

2024-11-20 10:23 UTC, retrokiller543 commented on src/chat.rs
> +    let file_data = fs::read_to_string("prompt.json").expect("unable to read prompt.json");
either put this in the state, use async to read from FS with `tokio`, or load the string into a const a compile time using `include_str!` macro to avoid any heavy IO operations during a request as much as possible. And preferably when we need to do IO in a request we should lean towards async to keep it open to handle other requests while we wait for IO to finish.

2024-11-20 10:23 UTC, retrokiller543 commented on prompt.json
> +        "prompt_template": "Here is information about the threat group :\nName: {name}\nDescription: {description}\nAssociated Names: {associated_names}\n\nQuestion: What are the associated names for
could this `prompt_template` be extracted and put in one single entry and we reuse it and do string replacement on the group name?

2024-11-20 10:23 UTC, retrokiller543 commented on prompt.json
> +[
This whole file seems like it could be removed and replaced with a global const in the api where we only have a template, this makes it so we only need to load in the data and then we can use either the name or id from the data directly in the code to construct the prompt kinda like how we add the name, description and associated names to the prompt before sending it

2024-11-20 10:39 UTC, kebabohvo commented on prompt.json
> +        "prompt_template": "Here is information about the threat group :\nName: {name}\nDescription: {description}\nAssociated Names: {associated_names}\n\nQuestion: What are the associated names for
Yes, but I run into some problems when I do it, that it dosen't work. But I will try to fix it.

2024-11-20 14:29 UTC, retrokiller543 commented on src/state.rs
> +async fn load_prompts() -> Vec<Prompt> {
if we dont use tokio to read the file we dont need it to be async since no action in here is async. Swap `std::fs` to `tokio::fs` to use tokio instead or just leave it and remove the `async` tag

2024-11-24 11:35 UTC, writemorecode commented
No, I don't like this at all. I think it would be better to have users supply the response format with the request data (see example from OpenAI's API: https://platform.openai.com/docs/guides/structured-outputs).
I think we should allow users to upload their own context information (I have a PR for this feature). Also, have you checked how much the Llama 3.1 8B model already knows about the information in the MITRE threat actors JSON file?

2024-12-02 14:58 UTC, closed without merging